version: "3.1"
services:
  postgres:
    image: supabase/postgres
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped
    volumes:
    - ./volumes/db/data:/var/lib/postgresql/data
    - ./volumes/db/init:/docker-entrypoint-initdb.d
    # ports:
    # - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: PSQL_PASSWORD
      POSTGRES_DB: postgresql
  hasura:
    depends_on:
      - postgres
    image: hasura/graphql-engine
    ports:
    - "6000:8080"
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "postgres://docker:PSQL_PASSWORD@db:5432/postgresql"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
