# propose
mutation {
  insert_equity_one(object: {
    uid: "FR-297920657",
    name: "EPA:BNP",
    country: "FR",
    currency: "EUR",
    issuer: "BNP",
    share_number: 730372026,
    source: "manuel",
    user_id: 1
  }) {
    id
  }
}

mutation {
  propose(args: {
    class: "equity",
    uid: "FR-297920657",
    name: "EPA:BNP",
    country: "FR",
    currency: "EUR",
    issuer: "BNP",
    share_number: 730372026,
    source: "manuel",
    user_id: 1
  }) {
    id
  }
}

query {
  candidates {
    id
  }
}

query {
  candidates(where: {uid: {_eq: "FR123"}}) {
    id
  }
}

mutation {
  approve(args: {
    instrument_id: 1
  }) {
    id
  }
}

mutation {
  reject(args: {
    instrument_id: 2
  }) {
    id
  }
}

query {
  golden(args: {
    uid: "FR123"
  }) {
    name
    country
    currency
  }
}

---

# with query variables
mutation approve(
  $instrument_id: Int
) {
  approve(args: {
    instrument_id: $instrument_id,
  }) {
    id
  }
}

{
  "instrument_id": 1
}

---
